FORMAT: 1A
HOST: http://www.st-joris-turnhout.be

# SIJOT-3 API

Deze referentie hoort bij de API die Scouts en Gidsen Sint-Joris, Turnhout. Heeft ontwikkeld voor intern gebruik. 

## Authorisatie 

#### Authorization request headers 

Bij elke(*) request moet een *Authorization-header* worden meegegeven:

`X-Authorization: {Uw API sleutel}`

`{Uw API sleutel}` is een random gegenereerde JSON token. Die kan verkregen worden als admin in het controle
paneel van de website.

(*) Enkele endpoints zijn publiek. Hierbij is geen *Authorization-header* noodzakelijk. Het resultaat kan wel afhangen
van de *Authorization-header*

## Verhuringen [/api/lease]

### Oplijsting van alle verhuringen [GET]
    
+ Response 200 (application/json)

    + Headers
    
            X-Authorization: '<Uw API sleutel>'

    + Body 
    
            {
            }

### Bekijk een specifieke verhuring [GET /{verhuring_id}]
+ Parameters
    + verhuring_id (integer) - De id van de verhuring in the systeem.
    

### Maak een verhuring aan [POST]